# Generated by Django 4.2.5 on 2023-10-13 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaimNumber', models.IntegerField()),
                ('DateofCreation', models.DateField(auto_now_add=True)),
                ('DeduceEmailAddress', models.EmailField(max_length=30, null=True)),
                ('DTNumber', models.TextField()),
                ('Department', models.CharField(max_length=120)),
                ('Manager', models.CharField(max_length=120)),
                ('ExpenseDetails', models.CharField(max_length=120)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('accountscomments', models.TextField(blank=True, null=True)),
                ('accountstatus', models.CharField(max_length=20)),
                ('paymentstatus', models.CharField(default='', max_length=20)),
                ('claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimstatus_set', to='Claim.parentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptNumber', models.CharField(max_length=100)),
                ('ReceiptDate', models.DateField()),
                ('BillAttachment', models.FileField(default='default.pdf', max_length=254, upload_to='media/')),
                ('ExpenseHead', models.CharField(max_length=120)),
                ('ClaimAmount', models.PositiveIntegerField()),
                ('TotalClaimAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Remarks', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_models', to='Claim.parentmodel')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
