# Generated by Django 4.2.3 on 2023-10-19 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Claim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
